// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: forex/v1/forex.proto

package forexv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ForexClient is the client API for Forex service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ForexClient interface {
	GetRate(ctx context.Context, in *GetRateRequest, opts ...grpc.CallOption) (*GetRateResponse, error)
}

type forexClient struct {
	cc grpc.ClientConnInterface
}

func NewForexClient(cc grpc.ClientConnInterface) ForexClient {
	return &forexClient{cc}
}

func (c *forexClient) GetRate(ctx context.Context, in *GetRateRequest, opts ...grpc.CallOption) (*GetRateResponse, error) {
	out := new(GetRateResponse)
	err := c.cc.Invoke(ctx, "/biscuit.forex.v1.Forex/GetRate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ForexServer is the server API for Forex service.
// All implementations must embed UnimplementedForexServer
// for forward compatibility
type ForexServer interface {
	GetRate(context.Context, *GetRateRequest) (*GetRateResponse, error)
	mustEmbedUnimplementedForexServer()
}

// UnimplementedForexServer must be embedded to have forward compatible implementations.
type UnimplementedForexServer struct {
}

func (UnimplementedForexServer) GetRate(context.Context, *GetRateRequest) (*GetRateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRate not implemented")
}
func (UnimplementedForexServer) mustEmbedUnimplementedForexServer() {}

// UnsafeForexServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ForexServer will
// result in compilation errors.
type UnsafeForexServer interface {
	mustEmbedUnimplementedForexServer()
}

func RegisterForexServer(s grpc.ServiceRegistrar, srv ForexServer) {
	s.RegisterService(&Forex_ServiceDesc, srv)
}

func _Forex_GetRate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForexServer).GetRate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/biscuit.forex.v1.Forex/GetRate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForexServer).GetRate(ctx, req.(*GetRateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Forex_ServiceDesc is the grpc.ServiceDesc for Forex service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Forex_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "biscuit.forex.v1.Forex",
	HandlerType: (*ForexServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRate",
			Handler:    _Forex_GetRate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "forex/v1/forex.proto",
}
