// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        (unknown)
// source: forex/v1/forex.proto

package forexv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From       string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To         string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Historical bool                   `protobuf:"varint,3,opt,name=historical,proto3" json:"historical,omitempty"`
	Timestamp  *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *GetRateRequest) Reset() {
	*x = GetRateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_forex_v1_forex_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRateRequest) ProtoMessage() {}

func (x *GetRateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_forex_v1_forex_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRateRequest.ProtoReflect.Descriptor instead.
func (*GetRateRequest) Descriptor() ([]byte, []int) {
	return file_forex_v1_forex_proto_rawDescGZIP(), []int{0}
}

func (x *GetRateRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *GetRateRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *GetRateRequest) GetHistorical() bool {
	if x != nil {
		return x.Historical
	}
	return false
}

func (x *GetRateRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type GetRateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *GetRateResponse) Reset() {
	*x = GetRateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_forex_v1_forex_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRateResponse) ProtoMessage() {}

func (x *GetRateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_forex_v1_forex_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRateResponse.ProtoReflect.Descriptor instead.
func (*GetRateResponse) Descriptor() ([]byte, []int) {
	return file_forex_v1_forex_proto_rawDescGZIP(), []int{1}
}

func (x *GetRateResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_forex_v1_forex_proto protoreflect.FileDescriptor

var file_forex_v1_forex_proto_rawDesc = []byte{
	0x0a, 0x14, 0x66, 0x6f, 0x72, 0x65, 0x78, 0x2f, 0x76, 0x31, 0x2f, 0x66, 0x6f, 0x72, 0x65, 0x78,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x62, 0x69, 0x73, 0x63, 0x75, 0x69, 0x74, 0x2e,
	0x66, 0x6f, 0x72, 0x65, 0x78, 0x2e, 0x76, 0x31, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8e, 0x01, 0x0a, 0x0e, 0x47, 0x65,
	0x74, 0x52, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x66, 0x72, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d,
	0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x74, 0x6f,
	0x12, 0x1e, 0x0a, 0x0a, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x69, 0x63, 0x61, 0x6c, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x69, 0x63, 0x61, 0x6c,
	0x12, 0x38, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52,
	0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x27, 0x0a, 0x0f, 0x47, 0x65,
	0x74, 0x52, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x32, 0x59, 0x0a, 0x05, 0x46, 0x6f, 0x72, 0x65, 0x78, 0x12, 0x50, 0x0a, 0x07,
	0x47, 0x65, 0x74, 0x52, 0x61, 0x74, 0x65, 0x12, 0x20, 0x2e, 0x62, 0x69, 0x73, 0x63, 0x75, 0x69,
	0x74, 0x2e, 0x66, 0x6f, 0x72, 0x65, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x62, 0x69, 0x73, 0x63,
	0x75, 0x69, 0x74, 0x2e, 0x66, 0x6f, 0x72, 0x65, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74,
	0x52, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x37,
	0x5a, 0x35, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x66, 0x69, 0x6e,
	0x65, 0x62, 0x69, 0x73, 0x63, 0x75, 0x69, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62,
	0x69, 0x73, 0x63, 0x75, 0x69, 0x74, 0x2f, 0x66, 0x6f, 0x72, 0x65, 0x78, 0x2f, 0x76, 0x31, 0x3b,
	0x66, 0x6f, 0x72, 0x65, 0x78, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_forex_v1_forex_proto_rawDescOnce sync.Once
	file_forex_v1_forex_proto_rawDescData = file_forex_v1_forex_proto_rawDesc
)

func file_forex_v1_forex_proto_rawDescGZIP() []byte {
	file_forex_v1_forex_proto_rawDescOnce.Do(func() {
		file_forex_v1_forex_proto_rawDescData = protoimpl.X.CompressGZIP(file_forex_v1_forex_proto_rawDescData)
	})
	return file_forex_v1_forex_proto_rawDescData
}

var file_forex_v1_forex_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_forex_v1_forex_proto_goTypes = []interface{}{
	(*GetRateRequest)(nil),        // 0: biscuit.forex.v1.GetRateRequest
	(*GetRateResponse)(nil),       // 1: biscuit.forex.v1.GetRateResponse
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_forex_v1_forex_proto_depIdxs = []int32{
	2, // 0: biscuit.forex.v1.GetRateRequest.timestamp:type_name -> google.protobuf.Timestamp
	0, // 1: biscuit.forex.v1.Forex.GetRate:input_type -> biscuit.forex.v1.GetRateRequest
	1, // 2: biscuit.forex.v1.Forex.GetRate:output_type -> biscuit.forex.v1.GetRateResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_forex_v1_forex_proto_init() }
func file_forex_v1_forex_proto_init() {
	if File_forex_v1_forex_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_forex_v1_forex_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_forex_v1_forex_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_forex_v1_forex_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_forex_v1_forex_proto_goTypes,
		DependencyIndexes: file_forex_v1_forex_proto_depIdxs,
		MessageInfos:      file_forex_v1_forex_proto_msgTypes,
	}.Build()
	File_forex_v1_forex_proto = out.File
	file_forex_v1_forex_proto_rawDesc = nil
	file_forex_v1_forex_proto_goTypes = nil
	file_forex_v1_forex_proto_depIdxs = nil
}
